### ISSUE TITLE
I'm watching you 😄 

### ISSUE THREAD

**Issue by moroine** [stanley92/blog-article-app#1]

**Comment by stanley92** [comment]
Any comments on this? I did this in about 4-5 hours. Let me know how I can improve especially on the server side.

**Comment by moroine** [comment]
Hey, here is a quick review:

- Do not commit `.DS_Store`
- I'd advise you to try https://www.mongodb.com/cloud/atlas & https://www.serverless.com/  to deploy you server for free 😄 
- No tests 😛 
- You can use `async/await` server-side
- I personally advise you to use functional components instead
- `axios` is deprecated

You could also have a look at NextJs which is awesome

But overall, looks good 👍
